opencv的逻辑运算

In [8]:
import cv2
import numpy as np

In [2]:
# 异或
print(1^1)

0


In [4]:
# opencv中的与或非是对应位置元素进行与或非、异或
print(204&213)
# 先转为2进制再进行运算


196


In [10]:
jm1 = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day1/JM.jpeg")
jm2 = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day5/JM2.jpeg")

# 非操作
jm1_not = cv2.bitwise_not(jm1)

print(jm1[:2,:2])
print("---------")
print(jm1_not[:2,:2])

list = [jm1,jm1_not]
cv2.imshow("jm",np.hstack(list))

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[207 208 206]
  [207 208 206]]

 [[203 204 202]
  [203 204 202]]]
---------
[[[48 47 49]
  [48 47 49]]

 [[52 51 53]
  [52 51 53]]]


In [ ]:
# 与操作 图片的对应位
jm1_new = jm1[:360,:360]
jm2_new = jm2[:360,:360]

jm_and = cv2.bitwise_and(jm1_new,jm2_new)

print(jm_and[:2,:2])

list = [jm1_new,jm2_new,jm_and]
cv2.imshow('jm',np.hstack(list))

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# 或操作
jm_or = cv2.bitwise_or(jm1_new,jm2_new)
                       
print(jm_or[:2,:2])

list = [jm1_new,jm2_new,jm_or]
cv2.imshow('jm',np.hstack(list))

cv2.waitKey(0)