# 形态学

利用0、1取值的卷积核进行提取输入图像的形状和特征
一般处理的都是二进制图像


## 图像二值化
方便进行形态学处理  

In [ ]:
'''
maxval:最大值，不一定是255
'''

import cv2
import numpy as np

# 全局二值化

img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day5/JM2.jpeg")

# 二值化是对灰度图像进行的，先进行灰度转化
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


# 函数返回两个值，设定的阈值和二值化图片
thr, dst = cv2.threshold(img_gray,thresh=80,maxval=255,type=cv2.THRESH_BINARY) # 二值化图片的像素点只有0或maxval


cv2.imshow("res",np.hstack([img_gray,dst]))

cv2.waitKey(0)
cv2.destroyAllWindows()

## 自适应阈值二值化

根据图像上的每一块小区域计算阈值

>> 阈值的取值？

1. 阈值取自相邻区域的平均值
2. 阈值取自相邻区域的加权和，权重为高斯窗口

In [ ]:
import cv2
import numpy as np

'''
maxval:最大值，不一定是255
blockSize:邻域大小
C:阈值等于平均值减去这个常数C
'''

import cv2
import numpy as np

# 全局二值化

img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day5/JM2.jpeg")

# 二值化是对灰度图像进行的，先进行灰度转化
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


# 只返回dst二值化图片
dst = cv2.adaptiveThreshold(img_gray,maxValue=255,adaptiveMethod=cv2.ADAPTIVE_THRESH_GAUSSIAN_C,thresholdType=cv2.THRESH_BINARY,blockSize=19,C=0)

cv2.imshow("res",np.hstack([img_gray,dst]))

cv2.waitKey(0)
cv2.destroyAllWindows()

## 腐蚀操作
对于卷积核，若其覆盖的每一点都是白色像素，则锚点设置为255，只要卷积核有黑色，就把整个区域辅食成为黑色

In [ ]:
import cv2
import numpy as np

'''
iterations:腐蚀操作的次数，迭代次数越多，腐蚀越明显
'''

img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day5/JM2.jpeg")

# 定义核
kernal = np.ones((3,3),np.uint8)
dst = cv2.erode(img,kernel=kernal,iterations=1)

cv2.imshow("dst",np.hstack([img,dst]))

cv2.waitKey(0)
cv2.destroyAllWindows()

## 获取结构元（形态学卷积核）

API中的shape是卷积核的形状，不是长宽，而是卷积核中1形成的形状

In [1]:
import cv2
import numpy as np

kernal = cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))
print(kernal)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [2]:
import cv2
import numpy as np

kernal = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(15,15))
print(kernal)

[[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 1 1 1 1 1 0 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 0 1 1 1 1 1 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]]


In [3]:
import cv2
import numpy as np

kernal = cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))
print(kernal)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [ ]:
import cv2
import numpy as np

'''
iterations:腐蚀操作的次数，迭代次数越多，腐蚀越明显
'''

img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day5/JM2.jpeg")

# 定义核，利用获取的形态学卷积核进行
kernal = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3))

dst = cv2.erode(img,kernel=kernal,iterations=1)

cv2.imshow("dst",np.hstack([img,dst]))

cv2.waitKey(0)
cv2.destroyAllWindows()

## 膨胀操作

腐蚀操作的逆过程，只要保证卷积核的锚点是非0值，则周边的的值都变成非0值

In [1]:
import cv2
import numpy as np

img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day5/JM2.jpeg")

kernal = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3))
dst = cv2.dilate(img,kernel=kernal,iterations=3)

cv2.imshow('large',np.hstack([img,dst]))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2
import numpy as np

img_ori = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day5/ed.jpeg")
img = cv2.cvtColor(img_ori,cv2.COLOR_BGR2GRAY)

kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3))

#先腐蚀
img_erode = cv2.erode(img,kernel=kernel,iterations=1)

#再膨胀
img_dilate = cv2.dilate(img_erode,kernel=kernel,iterations=1)

cv2.imshow('dst',np.hstack([img,img_erode,img_dilate]))

cv2.waitKey(0)
cv2.destroyAllWindows()

## 开运算

腐蚀之后再进行膨胀
提供一种去除噪声的思路，对原图无损伤

In [ ]:
import cv2
import numpy as np

img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day7/noise.jpeg")

# 手动实现开运算

k = cv2.getStructuringElement(cv2.MORPH_RECT,(3,3))

# 先腐蚀
dst = cv2.erode(img,kernel=k,iterations=1)
# 再膨胀
dst = cv2.dilate(dst,kernel=k,iterations=1)

cv2.imshow("dst",np.hstack([img,dst]))

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day7/noise.jpeg")


k = cv2.getStructuringElement(cv2.MORPH_RECT,(3,3))

dst = cv2.morphologyEx(img,cv2.MORPH_OPEN,k,2)

cv2.imshow("dst",np.hstack([img,dst]))

cv2.waitKey(0)
cv2.destroyAllWindows()

## 闭运算
先膨胀再腐蚀
只要用来去除图像内部的噪声

In [1]:
import cv2
import numpy as np

img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day7/noise.jpeg")

k = cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))

dst = cv2.morphologyEx(img,cv2.MORPH_CLOSE,k,2)

cv2.imshow("dst",np.hstack([img,dst]))

cv2.waitKey(0)
cv2.destroyAllWindows()

## 形态学梯度
原图-腐蚀后的图

得到图像的边缘细线，即梯度

In [ ]:
import cv2
import numpy as np

ed = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day5/ed.jpeg")

kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3,3))

# 直接调用opencv的API
dst = cv2.morphologyEx(ed,cv2.MORPH_GRADIENT,kernel,iterations=1)

cv2.imshow("dst",np.hstack([ed,dst]))

cv2.waitKey(0)
cv2.destroyAllWindows()

## 顶帽运算
原图-开运算
开运算得到图像外部的噪声点，顶帽的到的是去掉的噪声点

In [ ]:
import cv2
import numpy as np

ed = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day5/ed.jpeg")

kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3,3))

# 直接调用opencv的API
dst = cv2.morphologyEx(ed,cv2.MORPH_TOPHAT,kernel,iterations=1)

cv2.imshow("dst",np.hstack([ed,dst]))

cv2.waitKey(0)
cv2.destroyAllWindows()

## 黑帽操作
闭运算得到图像内部的噪声点，黑帽操作是原图-闭运算
得到的是图像内的噪声点


In [1]:
import cv2
import numpy as np

ed = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day5/ed.jpeg")

kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3,3))

# 直接调用opencv的API
dst = cv2.morphologyEx(ed,cv2.MORPH_BLACKHAT,kernel,iterations=1)

cv2.imshow("dst",np.hstack([ed,dst]))

cv2.waitKey(0)
cv2.destroyAllWindows()