# 图像轮廓

## 查找轮廓

具有相同灰度的连续点连成的曲线
检测轮廓时应该先二值化操作或者caany操作

绘制轮廓默认是直接在原图上绘制，修改了原图


In [ ]:
import cv2
import numpy as np

'''
mode:查找轮廓的模式
RETR_EXTERNAL = 0 只检测外围轮廓
RETR_LIST = 1 检测所有轮廓，轮廓之间没有等级关系
RETR_CCOMP = 2 每层做多两级
RETR_TREE = 3 按照树形存储轮廓，从右到左，从大到小索引

method:轮廓的近似方法
CHAIN_APPROX_NONE 保存轮廓上的所有点
CHAIN_APPROX_SIMPLE 保存轮廓上的角点，存储的信息较少

函数返回轮廓contours轮廓和hierarchy轮廓的层级

'''

img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day7/contour.jpeg")

# 先变为单通道的图片
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print(img_gray.shape)

# 对图片进行二值化
threshold, binary = cv2.threshold(img_gray,150,255,cv2.THRESH_BINARY)

# 进行轮廓查找
contours, hierarchy = cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

print(contours)
print("------")
print(hierarchy)

# cv2.imshow("img",img_gray)

# cv2.waitKey(0)
# cv2.destroyAllWindows()


## 绘制图像轮廓

In [ ]:

'''
 contourIdx:-1表示绘制所有的轮廓
 thickness:线宽，-1表示全部填充
'''
import cv2
import numpy as np



img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day7/contour.jpeg")

# 先变为单通道的图片
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print(img_gray.shape)

# 对图片进行二值化
threshold, binary = cv2.threshold(img_gray,150,255,cv2.THRESH_BINARY)

# 进行轮廓查找
contours, hierarchy = cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

cv2.drawContours(binary,contours,contourIdx=-1,color=(0,0,255),thickness=1)
cv2.drawContours(img_gray,contours,contourIdx=-1,color=(0,0,255),thickness=1)

cv2.imshow("img",img_gray)
cv2.imshow("binary",binary)
cv2.waitKey(0)
cv2.destroyAllWindows()


(810, 1080)


## 轮廓的面积和周长

周长中的closed参数，表征轮廓是否是闭合的

In [1]:

import cv2
import numpy as np

img = cv2.imread("/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day7/contour.jpeg")

# 先变为单通道的图片
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print(img_gray.shape)

# 对图片进行二值化
threshold, binary = cv2.threshold(img_gray,150,255,cv2.THRESH_BINARY)

# 进行轮廓查找
contours, hierarchy = cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

# cv2.drawContours(binary,contours,contourIdx=-1,color=(0,0,255),thickness=1)
cv2.drawContours(img,contours,contourIdx=0,color=(0,255,0),thickness=10)

# 计算轮廓的面积
area = cv2.contourArea(contours[0])
print(contours[0])
print("area = ",area)

# 计算轮廓的周长
length = cv2.arcLength(contours[0],closed=True)
print("length = ",length)

cv2.imshow("img",img)
# cv2.imshow("binary",binary)
cv2.waitKey(0)
cv2.destroyAllWindows()


(810, 1080)
[[[ 25 277]]

 [[ 24 278]]

 [[ 24 279]]

 [[ 23 280]]

 [[ 19 280]]

 [[ 18 281]]

 [[ 16 281]]

 [[ 15 282]]

 [[ 12 282]]

 [[ 12 283]]

 [[ 11 284]]

 [[  8 284]]

 [[  7 285]]

 [[  4 285]]

 [[  3 286]]

 [[  1 286]]

 [[  0 287]]

 [[  0 324]]

 [[  1 323]]

 [[  5 323]]

 [[  6 322]]

 [[  7 322]]

 [[  7 321]]

 [[  8 320]]

 [[  8 319]]

 [[  9 318]]

 [[  9 316]]

 [[ 10 315]]

 [[ 11 315]]

 [[ 11 312]]

 [[ 12 311]]

 [[ 12 310]]

 [[ 13 309]]

 [[ 13 308]]

 [[ 14 307]]

 [[ 15 307]]

 [[ 15 306]]

 [[ 16 305]]

 [[ 16 304]]

 [[ 17 303]]

 [[ 17 301]]

 [[ 20 298]]

 [[ 20 296]]

 [[ 21 295]]

 [[ 22 295]]

 [[ 22 294]]

 [[ 24 292]]

 [[ 24 290]]

 [[ 25 289]]

 [[ 26 289]]

 [[ 26 288]]

 [[ 27 287]]

 [[ 27 285]]

 [[ 30 282]]

 [[ 30 280]]

 [[ 29 280]]

 [[ 28 279]]

 [[ 28 278]]

 [[ 27 277]]]
area =  708.5
length =  135.8406194448471
