mat的深浅拷贝

In [1]:
# opencv 用mat数据结构保存图片，python中把mat转换为ndarray
# mat 类
import cv2
import numpy as np

In [6]:
# 读取图片
jm = cv2.imread('/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day1/JM.jpeg')

# 显示图片
cv2.imshow('jm', jm)

# 等待用户按键，按键后关闭窗口
if cv2.waitKey(10) == ord('q'):
    cv2.destroyAllWindows()

In [3]:
# python 中已经包装成了ndarray，所以对mat的深浅拷贝就是对ndarray的深浅拷贝
img = cv2.imread('/Users/duchengtai/Library/Mobile Documents/com~apple~CloudDocs/code- iCloud/opencv/day1/JM.jpeg')


# 浅拷贝
img2 = img.view()

# 深拷贝
img3 = img.copy()

img[10:100,10:100] = [0,0,255]  # 在img的部分区域加上红色色块，此时浅拷贝是共享底层数据的会改变，而深拷贝则不会

cv2.imshow('img',np.hstack((img,img2,img3)))

cv2.waitKey(0)
cv2.destroyAllWindows()

           



图像的分割与融合

In [ ]:
img = np.zeros((200,200,3),np.uint8)

# 图像分割
b, g, r = cv2.split(img)

print(b)

# 分割出每个通道，对每个通道的值进行修改
b[10:100,10:100] = 255
g[10:100,10:100] = 255

# 合并通道
img2 = cv2.merge((b,g,r))

cv2.imshow('img',np.hstack((img,img2)))
cv2.imshow('channel',np.hstack((b,g)))

cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
